import { SimulationResponse } from '@/lib/api/client'

export const DEMO_RESULT: SimulationResponse = {
  simulation_id: 'demo-123',
  address: '서울 서초구 언남9길 28',
  clinic_type: '정형외과',
  size_pyeong: 35,
  budget_million: 500,
  estimated_monthly_revenue: {
    min: 45000000,
    avg: 65000000,
    max: 85000000,
  },
  estimated_monthly_cost: {
    rent: 8000000,
    labor: 15000000,
    utilities: 2000000,
    supplies: 5000000,
    other: 3000000,
    total: 33000000,
  },
  profitability: {
    monthly_profit_avg: 32000000,
    breakeven_months: 14,
    annual_roi_percent: 38,
  },
  competition: {
    radius_m: 1000,
    same_dept_count: 5,
    total_clinic_count: 42,
  },
  competitors: [
    { name: '서초정형외과의원', distance_m: 150, est_monthly_revenue: 70000000, years_open: 8, clinic_type: '정형외과', rating: 4.5, review_count: 234, specialty_detail: '척추/관절 전문' },
    { name: '언남정형외과', distance_m: 280, est_monthly_revenue: 55000000, years_open: 5, clinic_type: '정형외과', rating: 4.3, review_count: 156, specialty_detail: '스포츠의학 전문' },
    { name: '연세정형외과의원', distance_m: 420, est_monthly_revenue: 62000000, years_open: 12, clinic_type: '정형외과', rating: 4.7, review_count: 412, specialty_detail: '어깨/무릎 전문' },
    { name: '강남본정형외과', distance_m: 650, est_monthly_revenue: 80000000, years_open: 15, clinic_type: '정형외과', rating: 4.6, review_count: 523, specialty_detail: '재활/물리치료' },
    { name: '서초튼튼정형외과', distance_m: 780, est_monthly_revenue: 48000000, years_open: 3, clinic_type: '정형외과', rating: 4.2, review_count: 89, specialty_detail: '비수술 치료' },
  ],
  demographics: {
    population_1km: 45000,
    age_40_plus_ratio: 0.42,
    floating_population_daily: 85000,
  },
  confidence_score: 87,
  recommendation: 'POSITIVE',
  recommendation_reason: '유동인구가 많고 직장인 밀집 지역으로 정형외과 수요가 높습니다. 경쟁이 있으나 차별화 전략으로 충분히 경쟁 가능한 입지입니다.',
  region_stats: {
    vs_national_percent: 15,
    national_avg_revenue: 52000000,
    region_rank: 3,
    total_regions: 17,
    rank_percentile: 18,
  },
  revenue_detail: {
    daily_patients_min: 25,
    daily_patients_avg: 38,
    daily_patients_max: 52,
    avg_treatment_fee: 78000,
    insurance_ratio: 0.75,
    non_insurance_ratio: 0.25,
    new_patient_ratio: 0.35,
    return_patient_ratio: 0.65,
    avg_visits_per_patient: 3.2,
    seasonal_factor: { spring: 1.1, summer: 0.85, fall: 1.15, winter: 0.9 },
  },
  cost_detail: {
    rent_deposit: 80000000,
    rent_monthly: 7000000,
    maintenance_fee: 1000000,
    doctor_count: 1,
    nurse_count: 2,
    admin_count: 2,
    avg_nurse_salary: 3200000,
    avg_admin_salary: 2800000,
    equipment_monthly: 2000000,
    marketing_monthly: 3000000,
    insurance_monthly: 500000,
    supplies_monthly: 2500000,
    utilities_monthly: 1500000,
    initial_equipment: 180000000,
    initial_interior: 120000000,
    initial_other: 30000000,
  },
  profitability_detail: {
    monthly_profit_min: 18000000,
    monthly_profit_avg: 32000000,
    monthly_profit_max: 48000000,
    annual_profit_estimate: 384000000,
    profit_margin_percent: 49.2,
    operating_margin_percent: 52.5,
    total_investment: 450000000,
    payback_months: 14,
    irr_percent: 42.5,
    npv_3years: 520000000,
  },
  competition_detail: {
    radius_m: 1000,
    same_dept_count: 5,
    similar_dept_count: 8,
    total_clinic_count: 42,
    hospital_count: 2,
    competition_index: 45,
    competition_level: 'MEDIUM',
    market_saturation: 62,
    estimated_market_share: 8.5,
    potential_patients_monthly: 2800,
    nearest_same_dept_distance: 150,
    avg_distance_same_dept: 420,
  },
  demographics_detail: {
    population_500m: 18000,
    population_1km: 45000,
    population_3km: 125000,
    age_0_9: 0.08,
    age_10_19: 0.09,
    age_20_29: 0.15,
    age_30_39: 0.18,
    age_40_49: 0.20,
    age_50_59: 0.16,
    age_60_plus: 0.14,
    male_ratio: 0.48,
    female_ratio: 0.52,
    single_household_ratio: 0.35,
    family_household_ratio: 0.65,
    avg_household_income: 650,
    floating_population_daily: 85000,
    floating_peak_hour: '12:00-13:00',
    floating_weekday_avg: 92000,
    floating_weekend_avg: 65000,
    medical_utilization_rate: 0.78,
    avg_annual_visits: 18.5,
  },
  location_analysis: {
    subway_stations: [
      { name: '서초역', distance_m: 350, lines: ['2호선'] },
      { name: '교대역', distance_m: 650, lines: ['2호선', '3호선'] },
    ],
    bus_stops_count: 8,
    bus_routes_count: 15,
    transit_score: 88,
    parking_available: true,
    parking_spaces: 45,
    nearby_parking_lots: 3,
    parking_score: 75,
    building_type: '근린상가',
    building_age: 8,
    floor_info: '3층',
    elevator_available: true,
    nearby_facilities: { pharmacy: 5, restaurant: 32, cafe: 18, bank: 4 },
    commercial_district_type: '오피스 밀집 상권',
    commercial_score: 82,
    foot_traffic_rank: 'A',
    visibility_score: 78,
    main_road_facing: true,
  },
  growth_projection: {
    revenue_projection: { year1: 680000000, year2: 780000000, year3: 850000000 },
    growth_rate_year1: 15,
    growth_rate_year2: 12,
    growth_rate_year3: 9,
    avg_growth_rate: 12,
    development_plans: ['서초역 역세권 개발 예정 (2026)', 'GTX-C 교대역 환승역 확정', '서리풀공원 확장 계획'],
    population_growth_rate: 2.3,
    commercial_growth_rate: 4.5,
    year5_revenue_estimate: 95000000,
    year5_profit_estimate: 48000000,
    cumulative_profit_5years: 1850000000,
  },
  risk_analysis: {
    overall_risk_level: 'MEDIUM',
    overall_risk_score: 42,
    risk_factors: [
      { factor: '경쟁 심화', level: 'MEDIUM', description: '반경 1km 내 5개 경쟁 병원 존재', mitigation: '특화 진료 분야 차별화' },
      { factor: '임대료 상승', level: 'LOW', description: '연 3% 내외 상승 예상', mitigation: '장기 계약으로 상승률 협상' },
    ],
    competition_risk: 'MEDIUM',
    location_risk: 'LOW',
    market_risk: 'LOW',
    financial_risk: 'MEDIUM',
    opportunities: ['직장인 밀집 지역으로 점심시간/퇴근 후 환자 유입', '고령화로 정형외과 수요 지속 증가', 'GTX-C 개통 시 유동인구 증가 예상'],
  },
  ai_insights: {
    executive_summary: '서초구 언남동은 오피스 밀집 지역으로 직장인 대상 정형외과 개원에 적합합니다. 경쟁이 있으나 야간/주말 진료와 비수술 치료 특화로 차별화가 가능합니다. 초기 투자 대비 14개월 내 손익분기점 도달이 예상되며, 연 38% ROI가 기대됩니다.',
    strengths: ['오피스 밀집 지역 (직장인 환자 풍부)', '대중교통 접근성 우수 (지하철 2개역 도보권)', '신축 건물로 시설 경쟁력', '주변 약국 다수 (처방전 연계 용이)'],
    weaknesses: ['경쟁 병원 5개 존재', '주차 공간 제한적', '주말 유동인구 감소', '초기 인지도 구축 필요'],
    opportunities: ['GTX-C 개통으로 유동인구 증가 예상', '고령화로 정형외과 수요 증가', '비대면 진료 확대 트렌드', '기업 건강검진 연계 가능'],
    threats: ['대형병원 외래 환자 증가', '의료수가 동결 가능성', '인건비 상승 지속', '신규 경쟁 병원 진입 가능성'],
    recommended_strategies: ['야간/주말 진료로 직장인 접근성 강화', '비수술 치료 특화 (도수치료, 충격파 등)', '네이버 플레이스 최적화 및 리뷰 관리', '기업체 건강검진 연계 영업'],
    differentiation_points: ['야간 진료 (20시까지)', '토요일 오후 진료', '비수술 척추/관절 치료 전문', '최신 물리치료 장비 보유'],
    target_patient_groups: ['30-50대 사무직 직장인', '스포츠/운동 관련 부상 환자', '만성 근골격계 질환 환자', '교통사고 환자'],
    recommended_opening_season: '3월 또는 9월',
    opening_timing_reason: '환절기에 근골격계 질환 증가, 새 학기/분기 시작과 맞물려 건강 관심 증가',
    marketing_suggestions: ['네이버 플레이스 최적화 (키워드: 서초 정형외과)', '당근마켓 비즈프로필 운영', '인스타그램 건강 정보 콘텐츠', '주변 기업체 제휴 마케팅'],
    estimated_marketing_budget: 3000000,
  },
  is_unlocked: true,
  unlock_price: 9900,
  created_at: '2024-01-01T00:00:00.000Z',
}
