"""broker system migration - 013"""
import asyncio
import asyncpg
import os

SQL = (
    "DO $$ BEGIN CREATE TYPE brokerstatus AS ENUM "
    "('PENDING','ACTIVE','SUSPENDED','TERMINATED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE brokertier AS ENUM "
    "('JUNIOR','SENIOR','TEAM_LEAD','DIRECTOR'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE dealstatus AS ENUM "
    "('LEAD','CONTACTED','VIEWING_SCHEDULED','VIEWED',"
    "'NEGOTIATING','CONTRACT_PENDING','CONTRACTED',"
    "'CLOSED_WON','CLOSED_LOST'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE dealclosereason AS ENUM "
    "('COMPLETED','DOCTOR_CANCELLED','LANDLORD_CANCELLED',"
    "'PRICE_MISMATCH','LOCATION_MISMATCH','COMPETITOR',"
    "'CIRCUMVENTION','OTHER'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE commissiontype AS ENUM "
    "('PLATFORM','BROKER','LANDLORD'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE commissionpaymentstatus AS ENUM "
    "('PENDING','APPROVED','PAID','CANCELLED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE suspiciousactivitytype AS ENUM "
    "('DEAL_CLOSED_THEN_CONTRACTED','CONTACT_DETECTED',"
    "'RAPID_STATUS_CHANGE','EXTERNAL_CONTRACT_SUSPECTED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "DO $$ BEGIN CREATE TYPE boardcategory AS ENUM "
    "('NOTICE','QNA','TIP','DISCUSSION'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END $$;\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS brokers ("
    "id SERIAL PRIMARY KEY,"
    "user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,"
    "license_number VARCHAR(50),"
    "brokerage_office_name VARCHAR(200),"
    "brokerage_registration VARCHAR(100),"
    "display_name VARCHAR(100) NOT NULL,"
    "phone VARCHAR(20),"
    "email VARCHAR(200),"
    "profile_image_url VARCHAR(500),"
    "introduction TEXT,"
    "assigned_regions JSONB DEFAULT '[]'::jsonb,"
    "assigned_specialties JSONB DEFAULT '[]'::jsonb,"
    "tier brokertier NOT NULL DEFAULT 'JUNIOR',"
    "status brokerstatus NOT NULL DEFAULT 'PENDING',"
    "total_deals INTEGER NOT NULL DEFAULT 0,"
    "closed_won_deals INTEGER NOT NULL DEFAULT 0,"
    "total_commission_earned BIGINT NOT NULL DEFAULT 0,"
    "avg_deal_days DOUBLE PRECISION NOT NULL DEFAULT 0,"
    "current_active_deals INTEGER NOT NULL DEFAULT 0,"
    "commission_rate DOUBLE PRECISION NOT NULL DEFAULT 60.0,"
    "payout_bank VARCHAR(50),"
    "payout_account VARCHAR(50),"
    "payout_holder VARCHAR(50),"
    "is_verified BOOLEAN NOT NULL DEFAULT FALSE,"
    "verified_at TIMESTAMP,"
    "verification_docs JSONB DEFAULT '[]'::jsonb,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_broker_status ON brokers(status);\n"
    "CREATE INDEX IF NOT EXISTS ix_broker_tier ON brokers(tier);\n"
    "CREATE INDEX IF NOT EXISTS ix_broker_user ON brokers(user_id);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS brokerage_deals ("
    "id UUID PRIMARY KEY DEFAULT gen_random_uuid(),"
    "deal_number VARCHAR(30) NOT NULL UNIQUE,"
    "broker_id INTEGER REFERENCES brokers(id) ON DELETE SET NULL,"
    "doctor_id UUID REFERENCES users(id),"
    "listing_id UUID REFERENCES landlord_listings(id),"
    "title VARCHAR(300) NOT NULL,"
    "description TEXT,"
    "status dealstatus NOT NULL DEFAULT 'LEAD',"
    "close_reason dealclosereason,"
    "close_note TEXT,"
    "expected_rent_deposit BIGINT,"
    "expected_monthly_rent BIGINT,"
    "expected_premium BIGINT,"
    "expected_commission BIGINT,"
    "actual_rent_deposit BIGINT,"
    "actual_monthly_rent BIGINT,"
    "actual_premium BIGINT,"
    "actual_commission BIGINT,"
    "landlord_commission BIGINT DEFAULT 0,"
    "doctor_commission BIGINT DEFAULT 0,"
    "marketing_cost BIGINT DEFAULT 0,"
    "ad_cost BIGINT DEFAULT 0,"
    "viewing_scheduled_at TIMESTAMP,"
    "viewed_at TIMESTAMP,"
    "contract_date TIMESTAMP,"
    "move_in_date TIMESTAMP,"
    "admin_notes TEXT,"
    "broker_notes TEXT,"
    "activity_log JSONB DEFAULT '[]'::jsonb,"
    "circumvention_flag BOOLEAN NOT NULL DEFAULT FALSE,"
    "circumvention_reason TEXT,"
    "circumvention_flagged_at TIMESTAMP,"
    "lead_source VARCHAR(100),"
    "lead_score INTEGER DEFAULT 0,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_deal_status ON brokerage_deals(status);\n"
    "CREATE INDEX IF NOT EXISTS ix_deal_broker ON brokerage_deals(broker_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_deal_doctor ON brokerage_deals(doctor_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_deal_listing ON brokerage_deals(listing_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_deal_number ON brokerage_deals(deal_number);\n"
    "CREATE INDEX IF NOT EXISTS ix_deal_circumvention ON brokerage_deals(circumvention_flag);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS deal_commissions ("
    "id SERIAL PRIMARY KEY,"
    "deal_id UUID NOT NULL REFERENCES brokerage_deals(id) ON DELETE CASCADE,"
    "commission_type commissiontype NOT NULL,"
    "gross_amount BIGINT DEFAULT 0,"
    "tax_amount BIGINT DEFAULT 0,"
    "marketing_deduction BIGINT DEFAULT 0,"
    "ad_deduction BIGINT DEFAULT 0,"
    "net_amount BIGINT DEFAULT 0,"
    "payment_status commissionpaymentstatus NOT NULL DEFAULT 'PENDING',"
    "approved_at TIMESTAMP,"
    "approved_by UUID REFERENCES users(id),"
    "paid_at TIMESTAMP,"
    "payment_reference VARCHAR(200),"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_commission_deal ON deal_commissions(deal_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_commission_status ON deal_commissions(payment_status);\n"
    "CREATE INDEX IF NOT EXISTS ix_commission_type ON deal_commissions(commission_type);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS suspicious_activities ("
    "id SERIAL PRIMARY KEY,"
    "deal_id UUID REFERENCES brokerage_deals(id),"
    "doctor_id UUID REFERENCES users(id),"
    "broker_id INTEGER REFERENCES brokers(id),"
    "listing_id UUID REFERENCES landlord_listings(id),"
    "activity_type suspiciousactivitytype NOT NULL,"
    "severity VARCHAR(20) DEFAULT 'LOW',"
    "description TEXT,"
    "evidence JSONB DEFAULT '{}'::jsonb,"
    "is_resolved BOOLEAN NOT NULL DEFAULT FALSE,"
    "resolved_by UUID REFERENCES users(id),"
    "resolution_note TEXT,"
    "resolved_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_suspicious_type ON suspicious_activities(activity_type);\n"
    "CREATE INDEX IF NOT EXISTS ix_suspicious_resolved ON suspicious_activities(is_resolved);\n"
    "CREATE INDEX IF NOT EXISTS ix_suspicious_severity ON suspicious_activities(severity);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS broker_board_posts ("
    "id SERIAL PRIMARY KEY,"
    "author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "broker_id INTEGER REFERENCES brokers(id) ON DELETE SET NULL,"
    "category boardcategory NOT NULL DEFAULT 'DISCUSSION',"
    "title VARCHAR(300) NOT NULL,"
    "content TEXT NOT NULL,"
    "is_pinned BOOLEAN NOT NULL DEFAULT FALSE,"
    "view_count INTEGER NOT NULL DEFAULT 0,"
    "comment_count INTEGER NOT NULL DEFAULT 0,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_board_category ON broker_board_posts(category);\n"
    "CREATE INDEX IF NOT EXISTS ix_board_pinned ON broker_board_posts(is_pinned);\n"
    "CREATE INDEX IF NOT EXISTS ix_board_author ON broker_board_posts(author_id);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS broker_board_comments ("
    "id SERIAL PRIMARY KEY,"
    "post_id INTEGER NOT NULL REFERENCES broker_board_posts(id) ON DELETE CASCADE,"
    "author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "parent_id INTEGER REFERENCES broker_board_comments(id) ON DELETE CASCADE,"
    "content TEXT NOT NULL,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_comment_post ON broker_board_comments(post_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_comment_parent ON broker_board_comments(parent_id);\n"
)


async def run():
    db_url = os.environ.get("DATABASE_URL", "")
    if db_url.startswith("postgres://"):
        db_url = db_url.replace("postgres://", "postgresql://", 1)
    dsn = db_url.replace("postgresql+asyncpg://", "postgresql://")

    conn = await asyncpg.connect(dsn)
    try:
        await conn.execute(SQL)
        print("OK: 013_broker_system migration completed")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(run())
