"""claims v2 - HIRA codes, DUR, appeals, EDI, analytics - 015"""
import asyncio
import asyncpg
import os

SQL = (
    # ===== Enable pg_trgm extension =====
    "CREATE EXTENSION IF NOT EXISTS pg_trgm;\n"

    # ===== Extend existing enums =====
    # Add new values to claimstatus
    "ALTER TYPE claimstatus ADD VALUE IF NOT EXISTS 'AI_REVIEWING';\n"
    "ALTER TYPE claimstatus ADD VALUE IF NOT EXISTS 'EDI_RECEIVED';\n"
    "ALTER TYPE claimstatus ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';\n"
    "ALTER TYPE claimstatus ADD VALUE IF NOT EXISTS 'APPEALING';\n"
    "ALTER TYPE claimstatus ADD VALUE IF NOT EXISTS 'APPEAL_ACCEPTED';\n"
    "ALTER TYPE claimstatus ADD VALUE IF NOT EXISTS 'APPEAL_REJECTED';\n"

    # Add new values to claimitype
    "ALTER TYPE claimitype ADD VALUE IF NOT EXISTS 'INJECTION';\n"
    "ALTER TYPE claimitype ADD VALUE IF NOT EXISTS 'TEST';\n"
    "ALTER TYPE claimitype ADD VALUE IF NOT EXISTS 'MATERIAL';\n"
    "ALTER TYPE claimitype ADD VALUE IF NOT EXISTS 'IMAGING';\n"

    # ===== Create new enums =====
    "DO " + "$" + "$ BEGIN CREATE TYPE analysisstatus AS ENUM "
    "('PENDING','RUNNING','COMPLETED','FAILED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE durseverity AS ENUM "
    "('INFO','WARNING','CRITICAL','CONTRAINDICATED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE durchecktype AS ENUM "
    "('DRUG_DRUG','DRUG_AGE','DRUG_GENDER','DRUG_PREGNANCY','DRUG_DISEASE','DUPLICATE','OVERDOSE','DURATION'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE interactiontype AS ENUM "
    "('CONTRAINDICATED','MAJOR','MODERATE','MINOR'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE appealtype AS ENUM "
    "('FULL_REJECTION','PARTIAL_REJECTION','UNIT_PRICE','ADJUSTMENT'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE appealstatus AS ENUM "
    "('DRAFT','LETTER_GENERATED','REVIEW_PENDING','SUBMITTED','ACCEPTED','PARTIALLY_ACCEPTED','REJECTED','WITHDRAWN'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE edidirection AS ENUM "
    "('OUTBOUND','INBOUND'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE edimessagetype AS ENUM "
    "('CLAIM_SUBMIT','CLAIM_RECEIPT','REVIEW_RESULT','ADJUSTMENT_NOTICE','APPEAL_SUBMIT','APPEAL_RESULT','CODE_UPDATE'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE claimauditaction AS ENUM "
    "('CREATED','UPDATED','STATUS_CHANGED','AI_ANALYZED','DUR_CHECKED','EDI_SUBMITTED','EDI_RECEIVED',"
    "'APPEAL_CREATED','APPEAL_SUBMITTED','ITEM_ADDED','ITEM_REMOVED','ITEM_MODIFIED','BATCH_CREATED','EXPORTED','VIEWED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    # ===== Create reference tables first (before FK references) =====

    # ----- hira_fee_codes -----
    "CREATE TABLE IF NOT EXISTS hira_fee_codes ("
    "id SERIAL PRIMARY KEY,"
    "code VARCHAR(20) UNIQUE NOT NULL,"
    "name VARCHAR(500) NOT NULL,"
    "name_en VARCHAR(500),"
    "category VARCHAR(100),"
    "subcategory VARCHAR(100),"
    "unit_price BIGINT DEFAULT 0,"
    "relative_value DOUBLE PRECISION,"
    "specialty_codes TEXT[] DEFAULT '{}',"
    "insurance_type VARCHAR(20) DEFAULT 'COVERED',"
    "max_frequency INTEGER,"
    "frequency_period_days INTEGER,"
    "max_quantity INTEGER,"
    "effective_from DATE,"
    "effective_to DATE,"
    "is_active BOOLEAN DEFAULT TRUE,"
    "notes TEXT,"
    "related_codes TEXT[] DEFAULT '{}',"
    "last_synced_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_fee_code ON hira_fee_codes(code);\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_fee_category ON hira_fee_codes(category);\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_fee_active ON hira_fee_codes(is_active);\n"
    "\n"

    # ----- hira_disease_codes -----
    "CREATE TABLE IF NOT EXISTS hira_disease_codes ("
    "id SERIAL PRIMARY KEY,"
    "code VARCHAR(20) UNIQUE NOT NULL,"
    "name_kr VARCHAR(500) NOT NULL,"
    "name_en VARCHAR(500),"
    "chapter VARCHAR(10),"
    "block VARCHAR(20),"
    "category_code VARCHAR(10),"
    "is_chronic BOOLEAN DEFAULT FALSE,"
    "is_rare BOOLEAN DEFAULT FALSE,"
    "severity_level INTEGER,"
    "common_procedures TEXT[] DEFAULT '{}',"
    "common_medications TEXT[] DEFAULT '{}',"
    "effective_from DATE,"
    "effective_to DATE,"
    "is_active BOOLEAN DEFAULT TRUE,"
    "last_synced_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_disease_code ON hira_disease_codes(code);\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_disease_chapter ON hira_disease_codes(chapter);\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_disease_chronic ON hira_disease_codes(is_chronic);\n"
    "\n"

    # ----- hira_drug_codes -----
    "CREATE TABLE IF NOT EXISTS hira_drug_codes ("
    "id SERIAL PRIMARY KEY,"
    "code VARCHAR(30) UNIQUE NOT NULL,"
    "product_name VARCHAR(500) NOT NULL,"
    "ingredient_name VARCHAR(500),"
    "manufacturer VARCHAR(200),"
    "insurance_price BIGINT DEFAULT 0,"
    "insurance_type VARCHAR(20) DEFAULT 'COVERED',"
    "dur_ingredients TEXT[] DEFAULT '{}',"
    "atc_code VARCHAR(20),"
    "dosage_form VARCHAR(100),"
    "max_daily_dose DOUBLE PRECISION,"
    "max_single_dose DOUBLE PRECISION,"
    "dose_unit VARCHAR(20),"
    "is_narcotic BOOLEAN DEFAULT FALSE,"
    "is_antibiotic BOOLEAN DEFAULT FALSE,"
    "requires_monitoring BOOLEAN DEFAULT FALSE,"
    "effective_from DATE,"
    "effective_to DATE,"
    "is_active BOOLEAN DEFAULT TRUE,"
    "last_synced_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_drug_code ON hira_drug_codes(code);\n"
    "CREATE INDEX IF NOT EXISTS ix_hira_drug_atc ON hira_drug_codes(atc_code);\n"
    "\n"

    # ----- hira_code_change_logs -----
    "CREATE TABLE IF NOT EXISTS hira_code_change_logs ("
    "id SERIAL PRIMARY KEY,"
    "code_type VARCHAR(20) NOT NULL,"
    "code VARCHAR(30) NOT NULL,"
    "change_type VARCHAR(20) NOT NULL,"
    "old_value JSONB,"
    "new_value JSONB,"
    "effective_date DATE NOT NULL,"
    "description TEXT,"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_code_change_type ON hira_code_change_logs(code_type);\n"
    "CREATE INDEX IF NOT EXISTS ix_code_change_code ON hira_code_change_logs(code);\n"
    "CREATE INDEX IF NOT EXISTS ix_code_change_effective ON hira_code_change_logs(effective_date);\n"
    "\n"

    # ===== ALTER insurance_claims — add new columns =====
    # EDI fields
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS edi_message_id VARCHAR(50);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS edi_receipt_number VARCHAR(50);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS edi_submitted_at TIMESTAMP;\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS edi_result_code VARCHAR(20);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS edi_result_detail JSONB DEFAULT '{}';\n"
    # Provider / diagnosis fields
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS ykiho VARCHAR(20);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS specialty_code VARCHAR(10);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS primary_dx_code VARCHAR(20);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS secondary_dx_codes TEXT[] DEFAULT '{}';\n"
    # AI analysis versioning
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS ai_analysis_version INTEGER;\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS ai_model_version VARCHAR(50);\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS ai_peer_percentile DOUBLE PRECISION;\n"
    # Appeal tracking
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS has_appeal BOOLEAN DEFAULT FALSE;\n"
    "ALTER TABLE insurance_claims ADD COLUMN IF NOT EXISTS appeal_count INTEGER DEFAULT 0;\n"
    # New indexes on insurance_claims
    "CREATE INDEX IF NOT EXISTS ix_claim_ykiho ON insurance_claims(ykiho);\n"
    "CREATE INDEX IF NOT EXISTS ix_claim_primary_dx ON insurance_claims(primary_dx_code);\n"
    "\n"

    # ===== ALTER claim_items — add new columns =====
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS fee_code_id INTEGER REFERENCES hira_fee_codes(id) ON DELETE SET NULL;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS disease_code_id INTEGER REFERENCES hira_disease_codes(id) ON DELETE SET NULL;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS drug_code_id INTEGER REFERENCES hira_drug_codes(id) ON DELETE SET NULL;\n"
    # DUR check fields
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS dur_checked BOOLEAN DEFAULT FALSE;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS dur_result VARCHAR(20);\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS dur_warnings JSONB DEFAULT '[]';\n"
    # AI analysis fields
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS ai_pass_rate_historical DOUBLE PRECISION;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS ai_pass_rate_model DOUBLE PRECISION;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS ai_alternative_codes JSONB DEFAULT '[]';\n"
    # Frequency fields
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS frequency_count INTEGER;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS frequency_limit INTEGER;\n"
    "ALTER TABLE claim_items ADD COLUMN IF NOT EXISTS frequency_period VARCHAR(20);\n"
    # New index on claim_items
    "CREATE INDEX IF NOT EXISTS ix_claim_item_type ON claim_items(item_type);\n"
    "\n"

    # ===== Create new tables =====

    # ----- dur_check_logs -----
    "CREATE TABLE IF NOT EXISTS dur_check_logs ("
    "id SERIAL PRIMARY KEY,"
    "claim_id UUID REFERENCES insurance_claims(id) ON DELETE SET NULL,"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "check_type durchecktype NOT NULL,"
    "drug_codes TEXT[] DEFAULT '{}',"
    "disease_codes TEXT[] DEFAULT '{}',"
    "severity durseverity NOT NULL,"
    "message TEXT NOT NULL,"
    "detail JSONB DEFAULT '{}',"
    "patient_age INTEGER,"
    "patient_gender VARCHAR(1),"
    "acknowledged VARCHAR(20) DEFAULT 'PENDING',"
    "acknowledged_by VARCHAR(100),"
    "acknowledged_reason TEXT,"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_dur_check_claim ON dur_check_logs(claim_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_dur_check_user ON dur_check_logs(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_dur_check_severity ON dur_check_logs(severity);\n"
    "CREATE INDEX IF NOT EXISTS ix_dur_check_created ON dur_check_logs(created_at);\n"
    "\n"

    # ----- drug_interactions -----
    "CREATE TABLE IF NOT EXISTS drug_interactions ("
    "id SERIAL PRIMARY KEY,"
    "drug_code_a VARCHAR(30) NOT NULL,"
    "drug_code_b VARCHAR(30) NOT NULL,"
    "interaction_type interactiontype NOT NULL,"
    "severity durseverity NOT NULL,"
    "description TEXT NOT NULL,"
    "mechanism TEXT,"
    "clinical_effect TEXT,"
    "management TEXT,"
    "reference_source VARCHAR(100),"
    "reference_url VARCHAR(500),"
    "last_synced_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_drug_interaction_pair ON drug_interactions(drug_code_a, drug_code_b);\n"
    "CREATE INDEX IF NOT EXISTS ix_drug_interaction_a ON drug_interactions(drug_code_a);\n"
    "CREATE INDEX IF NOT EXISTS ix_drug_interaction_b ON drug_interactions(drug_code_b);\n"
    "CREATE INDEX IF NOT EXISTS ix_drug_interaction_severity ON drug_interactions(severity);\n"
    "\n"

    # ----- claim_analysis_results -----
    "CREATE TABLE IF NOT EXISTS claim_analysis_results ("
    "id SERIAL PRIMARY KEY,"
    "claim_id UUID NOT NULL REFERENCES insurance_claims(id) ON DELETE CASCADE,"
    "version INTEGER DEFAULT 1,"
    "model_version VARCHAR(50),"
    "status analysisstatus DEFAULT 'PENDING',"
    "overall_risk_score INTEGER,"
    "pass_probability DOUBLE PRECISION,"
    "risk_level VARCHAR(10),"
    "item_results JSONB DEFAULT '[]',"
    "peer_comparison JSONB DEFAULT '{}',"
    "optimization_suggestions JSONB DEFAULT '[]',"
    "pipeline_results JSONB DEFAULT '{}',"
    "analysis_duration_ms INTEGER,"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_analysis_claim ON claim_analysis_results(claim_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_analysis_claim_version ON claim_analysis_results(claim_id, version);\n"
    "CREATE INDEX IF NOT EXISTS ix_analysis_status ON claim_analysis_results(status);\n"
    "\n"

    # ----- rejection_patterns -----
    "CREATE TABLE IF NOT EXISTS rejection_patterns ("
    "id SERIAL PRIMARY KEY,"
    "specialty_code VARCHAR(10) NOT NULL,"
    "diagnosis_code VARCHAR(20) NOT NULL,"
    "treatment_code VARCHAR(20) NOT NULL,"
    "total_claims INTEGER DEFAULT 0,"
    "rejected_claims INTEGER DEFAULT 0,"
    "rejection_rate DOUBLE PRECISION DEFAULT 0.0,"
    "common_reasons JSONB DEFAULT '[]',"
    "period_start TIMESTAMP,"
    "period_end TIMESTAMP,"
    "last_updated TIMESTAMP DEFAULT NOW(),"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_rejection_pattern ON rejection_patterns(specialty_code, diagnosis_code, treatment_code);\n"
    "CREATE INDEX IF NOT EXISTS ix_rejection_rate ON rejection_patterns(rejection_rate);\n"
    "\n"

    # ----- peer_benchmarks -----
    "CREATE TABLE IF NOT EXISTS peer_benchmarks ("
    "id SERIAL PRIMARY KEY,"
    "period VARCHAR(10) NOT NULL,"
    "specialty_code VARCHAR(10) NOT NULL,"
    "region VARCHAR(50),"
    "sample_size INTEGER DEFAULT 0,"
    "avg_rejection_rate DOUBLE PRECISION DEFAULT 0.0,"
    "median_rejection_rate DOUBLE PRECISION DEFAULT 0.0,"
    "percentiles JSONB DEFAULT '{}',"
    "top_rejected_codes JSONB DEFAULT '[]',"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_peer_benchmark ON peer_benchmarks(period, specialty_code);\n"
    "\n"

    # ----- claim_appeals -----
    "CREATE TABLE IF NOT EXISTS claim_appeals ("
    "id UUID PRIMARY KEY DEFAULT gen_random_uuid(),"
    "claim_id UUID NOT NULL REFERENCES insurance_claims(id) ON DELETE CASCADE,"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "appeal_number VARCHAR(30) UNIQUE NOT NULL,"
    "appeal_type appealtype NOT NULL,"
    "status appealstatus DEFAULT 'DRAFT',"
    "rejected_items JSONB DEFAULT '[]',"
    "total_rejected_amount BIGINT DEFAULT 0,"
    "appealed_amount BIGINT DEFAULT 0,"
    "ai_generated_letter TEXT,"
    "ai_success_probability DOUBLE PRECISION,"
    "ai_reasoning JSONB DEFAULT '{}',"
    "final_letter TEXT,"
    "supporting_evidence JSONB DEFAULT '[]',"
    "submitted_at TIMESTAMP,"
    "deadline DATE,"
    "result_received_at TIMESTAMP,"
    "result_detail JSONB DEFAULT '{}',"
    "recovered_amount BIGINT DEFAULT 0,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_appeal_claim ON claim_appeals(claim_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_appeal_user ON claim_appeals(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_appeal_status ON claim_appeals(status);\n"
    "CREATE INDEX IF NOT EXISTS ix_appeal_number ON claim_appeals(appeal_number);\n"
    "\n"

    # ----- edi_message_logs -----
    "CREATE TABLE IF NOT EXISTS edi_message_logs ("
    "id SERIAL PRIMARY KEY,"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "batch_id INTEGER REFERENCES claim_batches(id) ON DELETE SET NULL,"
    "direction edidirection NOT NULL,"
    "message_type edimessagetype NOT NULL,"
    "message_id VARCHAR(50) UNIQUE NOT NULL,"
    "xml_message TEXT,"
    "message_size_bytes INTEGER,"
    "ykiho VARCHAR(20),"
    "http_method VARCHAR(10),"
    "http_url VARCHAR(500),"
    "http_status INTEGER,"
    "http_response_time_ms INTEGER,"
    "success BOOLEAN,"
    "error_code VARCHAR(20),"
    "error_message TEXT,"
    "retry_count INTEGER DEFAULT 0,"
    "max_retries INTEGER DEFAULT 3,"
    "claim_ids TEXT,"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_edi_user ON edi_message_logs(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_edi_batch ON edi_message_logs(batch_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_edi_direction ON edi_message_logs(direction);\n"
    "CREATE INDEX IF NOT EXISTS ix_edi_msg_type ON edi_message_logs(message_type);\n"
    "CREATE INDEX IF NOT EXISTS ix_edi_msg_id ON edi_message_logs(message_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_edi_created ON edi_message_logs(created_at);\n"
    "\n"

    # ----- claim_audit_logs -----
    "CREATE TABLE IF NOT EXISTS claim_audit_logs ("
    "id SERIAL PRIMARY KEY,"
    "claim_id UUID REFERENCES insurance_claims(id) ON DELETE SET NULL,"
    "user_id UUID REFERENCES users(id) ON DELETE SET NULL,"
    "action claimauditaction NOT NULL,"
    "entity_type VARCHAR(50) NOT NULL,"
    "entity_id VARCHAR(50),"
    "old_value JSONB,"
    "new_value JSONB,"
    "description TEXT,"
    "ip_address VARCHAR(45),"
    "user_agent VARCHAR(500),"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_claim ON claim_audit_logs(claim_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_user ON claim_audit_logs(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_action ON claim_audit_logs(action);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_created ON claim_audit_logs(created_at);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_entity ON claim_audit_logs(entity_type, entity_id);\n"
)


async def run():
    db_url = os.environ.get("DATABASE_URL", "")
    if db_url.startswith("postgres://"):
        db_url = db_url.replace("postgres://", "postgresql://", 1)
    dsn = db_url.replace("postgresql+asyncpg://", "postgresql://")

    conn = await asyncpg.connect(dsn)
    try:
        await conn.execute(SQL)
        print("OK: 015_claims_v2 migration completed")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(run())
