"""tax correction v2 migration - 016"""
import asyncio
import asyncpg
import os

SQL = (
    # ===== Extend existing enums =====

    # -- taxcorrectionstatus --
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'SCANNING';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'SCAN_COMPLETE';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'PENDING_DOCS';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'READY_TO_SUBMIT';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'NTS_RECEIVED';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'PARTIALLY_APPROVED';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'REFUND_PENDING';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'APPEAL';\n"
    "ALTER TYPE taxcorrectionstatus ADD VALUE IF NOT EXISTS 'CANCELED';\n"

    # -- deductioncategory --
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'EQUIPMENT_DEPRECIATION';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'EMPLOYMENT_TAX_CREDIT';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'YOUTH_EMPLOYMENT';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'CAREER_BREAK_WOMEN';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'RND_TAX_CREDIT';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'FACILITY_INVESTMENT';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'FAITHFUL_FILING';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'VAT_OPTIMIZATION';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'VEHICLE_EXPENSE';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'ENTERTAINMENT_WELFARE';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'RETIREMENT_PROVISION';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'STAFF_EDUCATION';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'PENSION_SAVINGS';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'HOUSING_FUND';\n"
    "ALTER TYPE deductioncategory ADD VALUE IF NOT EXISTS 'INSURANCE_PREMIUM';\n"

    # ===== Create new enum types =====

    "DO " + "$" + "$ BEGIN CREATE TYPE filingtype AS ENUM "
    "('INCOME_TAX','VAT','WITHHOLDING','LOCAL_INCOME'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE filingsyncstatus AS ENUM "
    "('PENDING','SYNCING','COMPLETED','FAILED','PARTIAL'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE taxscanstatus AS ENUM "
    "('PENDING','SCANNING','COMPLETED','FAILED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE findingseverity AS ENUM "
    "('HIGH','MEDIUM','LOW','INFO'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE documenttype AS ENUM "
    "('PURCHASE_RECEIPT','DEPRECIATION_SCHEDULE','EMPLOYMENT_CONTRACT',"
    "'PAYROLL_LEDGER','INSURANCE_CERTIFICATE','DONATION_RECEIPT',"
    "'EDUCATION_RECEIPT','MEDICAL_RECEIPT','LEASE_CONTRACT',"
    "'TAX_INVOICE','CREDIT_CARD_STATEMENT','BANK_STATEMENT',"
    "'RESEARCH_CERTIFICATE','OTHER'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE documentstatus AS ENUM "
    "('UPLOADED','OCR_PROCESSING','OCR_COMPLETED','CLASSIFIED','VERIFIED','REJECTED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE feesettlementstatus AS ENUM "
    "('PENDING','CALCULATED','INVOICED','PAID','OVERDUE','WAIVED','REFUNDED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE feepaymentmethod AS ENUM "
    "('BANK_TRANSFER','CREDIT_CARD','AUTO_DEDUCT'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE taxauditaction AS ENUM "
    "('CREATED','UPDATED','STATUS_CHANGED','AI_SCANNED','DOCUMENT_UPLOADED',"
    "'DOCUMENT_VERIFIED','HOMETAX_SYNCED','SUBMITTED','FEE_CALCULATED',"
    "'FEE_PAID','DEDUCTION_ADDED','DEDUCTION_REMOVED','ACCOUNTANT_REVIEWED',"
    "'EXPORTED','VIEWED'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    "DO " + "$" + "$ BEGIN CREATE TYPE hometaxauthtype AS ENUM "
    "('CERTIFICATE','SIMPLE_AUTH','DELEGATION'); "
    "EXCEPTION WHEN duplicate_object THEN NULL; END " + "$" + "$;\n"

    # ===== New tables (created BEFORE ALTER to satisfy FK references) =====

    # -- tax_filing_histories --
    "CREATE TABLE IF NOT EXISTS tax_filing_histories ("
    "id SERIAL PRIMARY KEY,"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "tax_year INTEGER NOT NULL,"
    "filing_type filingtype DEFAULT 'INCOME_TAX',"
    "filing_period VARCHAR(20),"
    "gross_income BIGINT DEFAULT 0,"
    "business_income BIGINT DEFAULT 0,"
    "salary_income BIGINT DEFAULT 0,"
    "other_income BIGINT DEFAULT 0,"
    "necessary_expenses BIGINT DEFAULT 0,"
    "expense_breakdown JSONB DEFAULT '{}',"
    "deductions_total BIGINT DEFAULT 0,"
    "deductions_breakdown JSONB DEFAULT '{}',"
    "credits_total BIGINT DEFAULT 0,"
    "credits_breakdown JSONB DEFAULT '{}',"
    "taxable_income BIGINT DEFAULT 0,"
    "calculated_tax BIGINT DEFAULT 0,"
    "final_tax BIGINT DEFAULT 0,"
    "tax_paid BIGINT DEFAULT 0,"
    "sync_status filingsyncstatus DEFAULT 'PENDING',"
    "synced_from VARCHAR(20),"
    "synced_at TIMESTAMP,"
    "raw_data JSONB DEFAULT '{}',"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_filing_history_user_year ON tax_filing_histories(user_id, tax_year);\n"
    "CREATE INDEX IF NOT EXISTS ix_filing_history_type ON tax_filing_histories(filing_type);\n"
    "CREATE INDEX IF NOT EXISTS ix_filing_history_sync ON tax_filing_histories(sync_status);\n"
    "\n"

    # -- tax_scan_results (MUST be before ALTER tax_corrections for FK) --
    "CREATE TABLE IF NOT EXISTS tax_scan_results ("
    "id SERIAL PRIMARY KEY,"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "scan_type VARCHAR(30) DEFAULT 'FULL',"
    "tax_years JSONB DEFAULT '[]',"
    "status taxscanstatus DEFAULT 'PENDING',"
    "findings JSONB DEFAULT '[]',"
    "total_findings INTEGER DEFAULT 0,"
    "peer_benchmark JSONB DEFAULT '{}',"
    "total_potential_refund BIGINT DEFAULT 0,"
    "total_tax_savings BIGINT DEFAULT 0,"
    "confidence DOUBLE PRECISION DEFAULT 0.0,"
    "started_at TIMESTAMP,"
    "completed_at TIMESTAMP,"
    "duration_ms INTEGER,"
    "model_version VARCHAR(50),"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_scan_result_user ON tax_scan_results(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_scan_result_status ON tax_scan_results(status);\n"
    "CREATE INDEX IF NOT EXISTS ix_scan_result_created ON tax_scan_results(created_at);\n"
    "\n"

    # -- tax_documents --
    "CREATE TABLE IF NOT EXISTS tax_documents ("
    "id UUID PRIMARY KEY DEFAULT gen_random_uuid(),"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "correction_id UUID REFERENCES tax_corrections(id) ON DELETE SET NULL,"
    "original_filename VARCHAR(500) NOT NULL,"
    "file_extension VARCHAR(10) NOT NULL,"
    "file_size_bytes INTEGER,"
    "mime_type VARCHAR(100),"
    "s3_bucket VARCHAR(100),"
    "s3_key VARCHAR(500),"
    "encryption_algorithm VARCHAR(20) DEFAULT 'AES-256-GCM',"
    "encryption_key_id VARCHAR(100),"
    "document_type documenttype DEFAULT 'OTHER',"
    "ai_classified_type VARCHAR(50),"
    "ai_classification_confidence INTEGER,"
    "tax_year INTEGER,"
    "deduction_category VARCHAR(50),"
    "ocr_status VARCHAR(20) DEFAULT 'PENDING',"
    "ocr_provider VARCHAR(30),"
    "ocr_result JSONB DEFAULT '{}',"
    "status documentstatus DEFAULT 'UPLOADED',"
    "verified_by VARCHAR(100),"
    "verified_at TIMESTAMP,"
    "rejection_reason TEXT,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_doc_user ON tax_documents(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_doc_correction ON tax_documents(correction_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_doc_type ON tax_documents(document_type);\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_doc_status ON tax_documents(status);\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_doc_year ON tax_documents(tax_year);\n"
    "\n"

    # -- tax_fee_settlements --
    "CREATE TABLE IF NOT EXISTS tax_fee_settlements ("
    "id UUID PRIMARY KEY DEFAULT gen_random_uuid(),"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,"
    "correction_id UUID NOT NULL REFERENCES tax_corrections(id) ON DELETE CASCADE,"
    "refund_amount BIGINT DEFAULT 0,"
    "actual_refund_amount BIGINT DEFAULT 0,"
    "base_fee BIGINT DEFAULT 0,"
    "vat BIGINT DEFAULT 0,"
    "total_fee BIGINT DEFAULT 0,"
    "fee_breakdown JSONB DEFAULT '[]',"
    "discount_rate DOUBLE PRECISION DEFAULT 0.0,"
    "discount_reason VARCHAR(200),"
    "adjusted_fee BIGINT,"
    "status feesettlementstatus DEFAULT 'PENDING',"
    "payment_method feepaymentmethod,"
    "payment_date TIMESTAMP,"
    "payment_reference VARCHAR(100),"
    "invoice_number VARCHAR(30) UNIQUE,"
    "invoice_issued_at TIMESTAMP,"
    "invoice_due_date TIMESTAMP,"
    "receipt_number VARCHAR(30),"
    "receipt_issued_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_fee_settlement_user ON tax_fee_settlements(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_fee_settlement_correction ON tax_fee_settlements(correction_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_fee_settlement_status ON tax_fee_settlements(status);\n"
    "\n"

    # -- tax_regulation_references --
    "CREATE TABLE IF NOT EXISTS tax_regulation_references ("
    "id SERIAL PRIMARY KEY,"
    "law_name VARCHAR(200) NOT NULL,"
    "article VARCHAR(50) NOT NULL,"
    "paragraph VARCHAR(50),"
    "sub_paragraph VARCHAR(50),"
    "deduction_category VARCHAR(50) NOT NULL,"
    "title VARCHAR(300) NOT NULL,"
    "description TEXT,"
    "deduction_limit BIGINT,"
    "deduction_rate DOUBLE PRECISION,"
    "eligibility_criteria JSONB DEFAULT '[]',"
    "required_documents TEXT[] DEFAULT '{}',"
    "applicable_specialties TEXT[] DEFAULT '{}',"
    "applicable_business_types TEXT[] DEFAULT '{}',"
    "effective_from DATE,"
    "effective_to DATE,"
    "is_active BOOLEAN DEFAULT TRUE,"
    "last_updated TIMESTAMP DEFAULT NOW(),"
    "source_url VARCHAR(500),"
    "notes TEXT,"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_reg_category ON tax_regulation_references(deduction_category);\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_reg_law ON tax_regulation_references(law_name);\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_reg_active ON tax_regulation_references(is_active);\n"
    "\n"

    # -- tax_peer_benchmarks --
    "CREATE TABLE IF NOT EXISTS tax_peer_benchmarks ("
    "id SERIAL PRIMARY KEY,"
    "period VARCHAR(10) NOT NULL,"
    "specialty VARCHAR(50) NOT NULL,"
    "region VARCHAR(50),"
    "sample_size INTEGER DEFAULT 0,"
    "avg_gross_income BIGINT DEFAULT 0,"
    "avg_necessary_expenses BIGINT DEFAULT 0,"
    "avg_expense_rate DOUBLE PRECISION DEFAULT 0.0,"
    "avg_deduction_total BIGINT DEFAULT 0,"
    "avg_deduction_by_category JSONB DEFAULT '{}',"
    "percentiles JSONB DEFAULT '{}',"
    "avg_correction_rate DOUBLE PRECISION DEFAULT 0.0,"
    "avg_refund_amount BIGINT DEFAULT 0,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_peer_benchmark_period_specialty ON tax_peer_benchmarks(period, specialty);\n"
    "\n"

    # -- tax_audit_logs --
    "CREATE TABLE IF NOT EXISTS tax_audit_logs ("
    "id SERIAL PRIMARY KEY,"
    "correction_id UUID REFERENCES tax_corrections(id) ON DELETE SET NULL,"
    "user_id UUID REFERENCES users(id) ON DELETE SET NULL,"
    "action taxauditaction NOT NULL,"
    "entity_type VARCHAR(50) NOT NULL,"
    "entity_id VARCHAR(50),"
    "old_value JSONB,"
    "new_value JSONB,"
    "description TEXT,"
    "ip_address VARCHAR(45),"
    "user_agent VARCHAR(500),"
    "created_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_log_correction ON tax_audit_logs(correction_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_log_user ON tax_audit_logs(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_log_action ON tax_audit_logs(action);\n"
    "CREATE INDEX IF NOT EXISTS ix_audit_log_created ON tax_audit_logs(created_at);\n"
    "\n"

    # -- hometax_credentials --
    "CREATE TABLE IF NOT EXISTS hometax_credentials ("
    "id SERIAL PRIMARY KEY,"
    "user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE,"
    "auth_type hometaxauthtype NOT NULL,"
    "encrypted_credential TEXT,"
    "encryption_key_id VARCHAR(100),"
    "credential_iv VARCHAR(50),"
    "tax_accountant_name VARCHAR(100),"
    "tax_accountant_license VARCHAR(30),"
    "delegation_start TIMESTAMP,"
    "delegation_end TIMESTAMP,"
    "delegation_scope JSONB DEFAULT '[]',"
    "is_active BOOLEAN DEFAULT TRUE,"
    "last_used_at TIMESTAMP,"
    "expires_at TIMESTAMP,"
    "created_at TIMESTAMP DEFAULT NOW(),"
    "updated_at TIMESTAMP DEFAULT NOW()"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_hometax_cred_user ON hometax_credentials(user_id);\n"
    "CREATE INDEX IF NOT EXISTS ix_hometax_cred_active ON hometax_credentials(is_active);\n"
    "\n"

    # ===== ALTER tax_corrections (after tax_scan_results exists) =====
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS nts_submission_id VARCHAR(50);\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS nts_submission_date TIMESTAMP;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS nts_result_date TIMESTAMP;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS nts_result_detail JSONB DEFAULT '{}';\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS actual_refund_amount BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS net_refund BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS original_deductions_total BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS new_deductions_total BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS tax_accountant_id VARCHAR(50);\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS tax_accountant_name VARCHAR(100);\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS tax_accountant_review TEXT;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS tax_accountant_approved BOOLEAN;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS ai_scan_id INTEGER REFERENCES tax_scan_results(id) ON DELETE SET NULL;\n"
    "ALTER TABLE tax_corrections ADD COLUMN IF NOT EXISTS peer_comparison JSONB DEFAULT '{}';\n"
    "CREATE INDEX IF NOT EXISTS ix_tax_correction_scan ON tax_corrections(ai_scan_id);\n"
    "\n"

    # ===== ALTER tax_deductions =====
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS original_amount BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS additional_amount BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS tax_savings BIGINT DEFAULT 0;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS tax_code_reference VARCHAR(100);\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS tax_code_article VARCHAR(50);\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS deduction_limit BIGINT;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS deduction_rate DOUBLE PRECISION;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS eligibility_criteria JSONB DEFAULT '[]';\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS ai_confidence DOUBLE PRECISION DEFAULT 0.0;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS ai_risk_note TEXT;\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS review_status VARCHAR(20) DEFAULT 'PENDING';\n"
    "ALTER TABLE tax_deductions ADD COLUMN IF NOT EXISTS reviewer_note TEXT;\n"
    "CREATE INDEX IF NOT EXISTS ix_deduction_review ON tax_deductions(review_status);\n"
)


async def run():
    db_url = os.environ.get("DATABASE_URL", "")
    if db_url.startswith("postgres://"):
        db_url = db_url.replace("postgres://", "postgresql://", 1)
    dsn = db_url.replace("postgresql+asyncpg://", "postgresql://")

    conn = await asyncpg.connect(dsn)
    try:
        await conn.execute(SQL)
        print("OK: 016_tax_correction_v2 migration completed")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(run())
